name:                adev
version:             0.1.0.0
github:              "alex-lew/adev"
license:             BSD3
author:              "Alex Lew"
maintainer:          "alexlew@mit.edu"
copyright:           "Copyright (c) 2022"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            probabilistic programming

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/alex-lew/adev#readme>

dependencies:
- base >= 4.7 && < 5
- monad-bayes >=1.1.0
- log-domain >=0.12 && <0.14
- mtl >=2.2.2 && <2.2.3
- ad >=4.5.2 && <4.5.3
- transformers >=0.5.6.2 && <0.5.6.3
- vector >=0.12.3.1 && <0.12.4

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  Figure2:
    main:                Figure2.hs
    source-dirs:         examples
    other-modules: []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adev
  ParticleFilterExample:
    main:                ParticleFilterExample.hs
    source-dirs:         examples
    other-modules: []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adev
  StochasticADExample:
    main:                StochasticADExample.hs
    source-dirs:         examples
    other-modules: []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adev

tests:
  adev-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adev
